version: '3'

services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: world